[tool.poetry]
name = "arvosanalaskuri"
version = "0.1.0"
description = ""
authors = ["Tony Lam <tony.lam@iki.fi>"]

[tool.poetry.dependencies]
python = "^3.8"
flask = "^3.0.0"
gunicorn = "^23.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
